# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest
  -task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'python -m venv env'
    script: 'call ./env/Scripts/activate.bat'
    script:  'pip install -r ./requirements.txt'
    script:  'pytest .\sample\MyFirstTest.py'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
