# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest
  -task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
                 python -m venv env
                 call ./env/Scripts/activate.bat
                 pip install -r ./requirements.txt
                 pytest .\sample\MyFirstTest.py

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


